## CSCI 470 Activities and Case Studies

1. For all activities, you are allowed to collaborate with a partner. 
1. For case studies, you should work individually and are **not** allowed to collaborate.

By filling out this notebook and submitting it, you acknowledge that you are aware of the above policies and are agreeing to comply with them.

# Optimization & Linear Algebra Review

In this exercise we will focus on the two main topics we covered in the lecture.

## Linear Algebra

In the lecture, with regards to Linear Algebra, we covered:

- some notation that we use for linear algebra
- special kinds of matrices
- matrix properties and operations
- norm definitions

Now let's practice some of these. 

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
plt.style.use("ggplot")

In numpy we can create a vector or matrix or tensor using the [`np.array`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) object.

In [2]:
vector = np.array([1,2,3])
print(vector)
print(f"The shape of our vector is {vector.shape}")

[1 2 3]
The shape of our vector is (3,)


In [3]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print(matrix)
print(f"The shape of our matrix is {matrix.shape}")

[[1 2 3]
 [4 5 6]]
The shape of our matrix is (2, 3)


In [4]:
tensor = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(tensor)
print(f"The shape of our tensor is {tensor.shape}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The shape of our tensor is (2, 2, 3)


### Products

Let's try out some products now and check how they work. By default, numpy would do element wise multiplication if we use the `*` operator. Instead, we can use the [`@`](https://docs.python.org/3/library/operator.html#mapping-operators-to-functions) operator. (This is valid as of Python 3.5, otherwise you can use [`np.matmul`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html)).

Let's start by making some vectors and matrices. 

In [5]:
x = np.array([[1,2,3]]) # a row vector
y = np.array([[4],[5],[6]]) # a column vector

In [6]:
print(x)

[[1 2 3]]


In [7]:
print(y)

[[4]
 [5]
 [6]]


We can determine an array's dimensions by calling [`.shape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html).

In [8]:
x.shape, y.shape

((1, 3), (3, 1))

Now let's try multiplying the two vectors to get their inner product. We'll also verify the result by manually calculating it.

In [9]:
x @ y, 1 * 4 + 2 * 5 + 3 * 6

(array([[32]]), 32)

Now let's look at how transpose works. With numpy, you can access the transpose of a `np.array` by calling its [`.T`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html) method or using [`np.transpose()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html). For simplicity, we will use `.T`.

In [10]:
print(x)
print(x.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


In this next cell we can see that if the shapes of two different objects do not align, the product will fail.

In [11]:
try:
    x.T @ y
except Exception as e:
    print(e)
    
try:
    x @ y.T
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)


In [12]:
x.shape, x.T.shape

((1, 3), (3, 1))

Squeezing gets rid of any shape dimensions with value = 1. This ensures a variable can be treated as a vector instead of a matrix with 1 row for example. Check out the documentation for [`.squeeze`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html).

In [13]:
x.shape, x.squeeze().shape

((1, 3), (3,))

In [14]:
x.T @ y.T

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

Now let's move on to matrices.

In [24]:
X = np.array([
    [1, 2],
    [3, 4]
])
Y = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
X.shape, Y.shape

((2, 2), (2, 3))

In [27]:
# Calculate the product of X and Y and save it to the variable `out`
# YOUR CODE HERE
#raise NotImplementedError()
out = X@Y

In [30]:
assert out.shape == (2,3)
assert out[0,0] == 1 * 1 + 2 * 4
assert out[1,1] == 3 * 2 + 4 * 5

In [31]:
print(f"The output shape of XY should be {X.shape[0]}, {Y.shape[1]}")
print(f"It is in fact, {out.shape} ")

The output shape of XY should be 2, 3
It is in fact, (2, 3) 


### Norms

Now let's calculate the norms that we discussed in the lecture.

#### Vector Norms

First, let's calculate the $\ell_1$ norm. We can calculate norms manually or using numpy's [`linalg.norm`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html) method.

In [32]:
ell_1_of_x = np.linalg.norm(x.squeeze(), 1)
sum_of_abs_of_x = np.abs(x).sum() 
print(ell_1_of_x, sum_of_abs_of_x)

6.0 6


Now calculate the $\ell_2$ norm of $\mathbf{x}$, once using the norm function and compare it to calculating it manually. Check the shape of $\mathbf{x}$ to make sure it is a vector. (You might need to use `.squeeze()`). 

In [53]:
# Use the norm function to calculate ell_2_of_x 
# Manually calculate the norm and save to manual_ell_2_of_x

# YOUR CODE HERE
#raise NotImplementedError()
ell_2_of_x = np.linalg.norm(x.squeeze(),2)
manual_ell_2_of_x = np.sqrt((x**2).sum())
print(ell_2_of_x,manual_ell_2_of_x )

3.7416573867739413 3.7416573867739413


In [54]:
assert ell_2_of_x == manual_ell_2_of_x

#### Matrix Norms

Test the multiple definitions of the Frobenius norm.

In [55]:
print(X)
result = []
for row in X:
    print(row)
    result.append(np.linalg.norm(row.flatten(), 2))
print(np.linalg.norm(result))

[[1 2]
 [3 4]]
[1 2]
[3 4]
5.477225575051661


In [56]:
np.linalg.norm(X)

5.477225575051661

In [58]:
print(np.sum(X**2)**0.5)

5.477225575051661


The trace of a matrix is the sum of its diagonal. With numpy we can calculate the trace of a matrix using [`np.trace`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.trace.html).

In [59]:
print(X)
np.diag(X).sum(), np.trace(X)

[[1 2]
 [3 4]]


(5, 5)

Test the relationship between the Frobenius norm and trace.

In [60]:
np.trace(X @ X.T)**0.5

5.477225575051661

### Special Matrices

Here we'll investigate the identity matrix, diagonal matrices, and symmetric matrices.

You can create an identity matrix using [`np.eye`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

In [61]:
five_identity = np.eye(5)
five_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

[`np.diag`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html) is used to either create a diagonal matrix or extract the diagonal of an existing matrix.

In [62]:
D = np.diag([1,2,3,4,5])
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [63]:
np.diag(five_identity)

array([1., 1., 1., 1., 1.])

We can check if a matrix is Symmetric by checking if it is equivalent to its transpose. Is a diagonal matrix symmetric?


In [64]:
print(f"It is {np.all(D == D.T)} that D is a symmetric matrix")

It is True that D is a symmetric matrix


In [65]:
print(f"It is {np.all(X == X.T)} that X is a symmetric matrix")

It is False that X is a symmetric matrix


We can calculate the rank of a matrix using [`np.linalg.matrix_rank`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.matrix_rank.html).

In [66]:
np.linalg.matrix_rank(X)

2

In [67]:
np.linalg.matrix_rank(five_identity)

5

In [68]:
np.linalg.matrix_rank(np.array([
    [1, 2, 3],
    [2, 4, 6]
]))

1

In [69]:
np.linalg.matrix_rank(np.array([
    [1, 2, 4],
    [2, 4, 6]
]))

2

Check to see if these numbers make sense to you based on the definition of rank.

## Decomposition

Now let's look at decomposing a matrix into multiple matrices. We have two main methods of doing so. Singular Value Decomposition works on all matrices and eigenvalue decomposition works on symmetric matrices.

We can use [`linalg.svd`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.svd.html) to calculate the SVD of a matrix and [`linalg.eig`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.eig.html) to form the eigenvalue decomposition of a symmetric matrix.

In [70]:
U, Sigma, VT = np.linalg.svd(Y)
V = VT.T
print(U)
print(V)
print(Sigma)
U@U.T, U.T @ U, V@V.T, V.T @ V

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
[[-0.42866713  0.80596391  0.40824829]
 [-0.56630692  0.11238241 -0.81649658]
 [-0.7039467  -0.58119908  0.40824829]]
[9.508032   0.77286964]


(array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[1.00000000e+00, 1.16059657e-16, 9.83171390e-17],
        [1.16059657e-16, 1.00000000e+00, 4.58633852e-19],
        [9.83171390e-17, 4.58633852e-19, 1.00000000e+00]]),
 array([[ 1.00000000e+00,  4.13108370e-17,  2.21870637e-17],
        [ 4.13108370e-17,  1.00000000e+00, -1.77008767e-16],
        [ 2.21870637e-17, -1.77008767e-16,  1.00000000e+00]]))

Check the orthogonality of the resulting matrices.

In [72]:
U@U.T, U.T @ U, V@V.T, V.T @ V

(array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -8.49433239e-18],
        [-8.49433239e-18,  1.00000000e+00]]),
 array([[1.00000000e+00, 1.16059657e-16, 9.83171390e-17],
        [1.16059657e-16, 1.00000000e+00, 4.58633852e-19],
        [9.83171390e-17, 4.58633852e-19, 1.00000000e+00]]),
 array([[ 1.00000000e+00,  4.13108370e-17,  2.21870637e-17],
        [ 4.13108370e-17,  1.00000000e+00, -1.77008767e-16],
        [ 2.21870637e-17, -1.77008767e-16,  1.00000000e+00]]))

Let's create a symmetric matrix $\mathbf{S}$ to verify SVD's equivalence to eigenvalue decomposition when the matrix is symmetric.

In [73]:
S = np.array([
    [1, 2, 3],
    [2, 3, 7],
    [3, 7, 12]
])

In [83]:
U, Sigma, VT = np.linalg.svd(S)
V = VT.T
print(U)
print(V)
print(Sigma)

[[-0.22380127 -0.26826216  0.93698901]
 [-0.47060372  0.87162146  0.13714285]
 [-0.85348997 -0.41025777 -0.32131516]]
[[-0.22380127  0.26826216  0.93698901]
 [-0.47060372 -0.87162146  0.13714285]
 [-0.85348997  0.41025777 -0.32131516]]
[16.64636961  0.91033134  0.26396173]


In [85]:
# Calculate the eigenvalues and eigenvectors of S and save them to eig_vals and eig_vecs respectively.
# YOUR CODE HERE
#raise NotImplementedError()
eig_vals, eig_vecs = np.linalg.eig(S)
print(f'Eigenvalues {eig_vals}')
print(f'Eigenvectors {eig_vecs}')

Eigenvalues [16.64636961  0.26396173 -0.91033134]
Eigenvectors [[ 0.22380127  0.93698901  0.26826216]
 [ 0.47060372  0.13714285 -0.87162146]
 [ 0.85348997 -0.32131516  0.41025777]]


In [86]:
assert eig_vals.shape == (3,)
assert eig_vecs.shape == (3,3)

Verify some properties of eigenvalues for symmetric matrices.

In [87]:
np.linalg.eigvals(S.T @ S), np.linalg.eigvals(S @ S.T), np.linalg.eigvals(S) ** 2

(array([2.77101621e+02, 6.96757948e-02, 8.28703141e-01]),
 array([2.77101621e+02, 6.96757948e-02, 8.28703141e-01]),
 array([2.77101621e+02, 6.96757948e-02, 8.28703141e-01]))

## Feedback

In [88]:
def feedback():
    """Provide feedback on the contents of this exercise
    
    Returns:
        string
    """
    # YOUR CODE HERE
    #raise NotImplementedError()
    return ('More examples pls!')